#!/usr/bin/env bash

################################
# Shows info about connected batteries.
#
# Dependencies:
# - acpi
################################

full=""
short=""
color=""
status=0


# Exit if no battery was found
if [ "$(acpi)" == "" ]; then exit 0; fi


state=$(acpi | sed -n 's/Battery [0-9]: \([A-Z]\).*, .*/\1/p')
chg=$(acpi | sed -n 's/Battery [0-9]:.*, \([0-9]\{1,3\}\)%.*/\1/p')


if [ "$state" = "C" ]; then
	icon=""
else
	if [ $chg -le 10 ]; then
		icon=""
		color="#47a8e9"
		status=33
	else
		icon=""
	fi
fi

full="$icon $chg%"
short="$chg%"

echo $full
echo $short
echo $color
exit $status
