#!/usr/bin/env bash

################################
# Shows info about the CPU
################################

full=""
short=""
color=""
status=0


calc() {
	echo "$1" | bc
}


read cpu a b c previdle rest < /proc/stat
prevtotal=$(calc "$a + $b + $c + $previdle")
sleep 0.5
read cpu a b c idle rest < /proc/stat
total=$(calc "$a + $b + $c + $idle")


CPU=$(calc "100 * (($total - $prevtotal) - ($idle - $previdle)) / ($total - $prevtotal)")


full="$CPU%"
short=$full

if [ $CPU -ge 90 ]; then
	color="#ff0000"
	status=33
fi


echo $full
echo $short
echo $color
exit $status
