#!/usr/bin/env bash

################################
# Shows current date
#
# @param {String} format: The format of the date
# @return {Date}: Current date
################################

dir=$(dirname $0)
source $dir/util.sh

format=${BLOCK_INSTANCE:-"%Y-%m-%d"}

date +"$format"
date +"%m-%d"
