#!/usr/bin/env bash

################################
# Shows current keyboard layout.
# Allows layout toggling.
#
# Dependencies:
# - [Ross' key script](https://github.com/rosshadden/dotfiles/blob/master/src/lib/keys.sh)
#
# @return {String}: Current keyboard layout
################################

dir=$(dirname $0)
source $dir/util.sh

full=""
short=""
color=""
status=0


case $BLOCK_BUTTON in

    # right click: toggle key variant
    3) keys toggle ;;

    # scroll up: change to dvorak
    4) keys dvorak ;;

    # scroll down: change to qwerty
    5) keys qwerty ;;

esac


layout=$($HOME/bin/keys get)

full=$layout
short=${layout:0:1}


echo $full
echo $short
echo $color
exit $status
