#!/usr/bin/env bash

################################
# Shows info about the RAM
################################

full=""
short=""
color=""
status=0


exec 6< /proc/meminfo
read a total b <&6
read a free b <&6


MEM=$(echo "100 * ($total - $free) / $total" | bc)


full="$MEM%"
short=$full

if [ $MEM -ge 80 ]; then
    color="#ff0000"
    status=33
fi


echo $full
echo $short
echo $color
exit $status
