#!/usr/bin/env bash

################################
# Shows ip address of a given interface
#
# @param {String} interface: The network interface to check
################################

full=""
short=""
color=""
status=0

interface=${BLOCK_INSTANCE:-"eth0"}


netPath=/sys/class/net
interfacePath=$(echo $netPath/$interface)
# Expand wildcard interfaces
interface=${interfacePath#$netPath/}

state=$(cat $interfacePath/operstate)

if [ $state == "up" ]; then
	ips=$(ip addr show $interface | perl -n -e'/inet (.+)\// && print $1')
	ip=${ips:-0.0.0.0}

	full=$ip
	short=$full
fi


echo $full
echo $short
echo $color
exit $status
