#!/usr/bin/env bash

################################
# Shows pacman packages that need updated.
#
# Dependencies:
# - checkupdates
################################

full=""
short=""
color=""
status=0


arch=$(checkupdates | wc -l)

if [ $arch -ne 0 ]; then
	full=$arch
	short=$full
fi


echo $full
echo $short
echo $color
exit $status
