#!/usr/bin/env bash

################################
# Shows pacman packages that need updated.
#
# Dependencies:
# - checkupdates
# - notify-send
################################

full=""
short=""
color=""
status=0


packages=`checkupdates`
numPackages=$(echo "$packages" | wc -l)

full=$numPackages
short=$full


echo $full
echo $short
echo $color


case $BLOCK_BUTTON in

	# right click: show packages
	3) notify-send "Pacman Packages" "$packages" ;;

esac


exit $status
