#!/usr/bin/env bash

################################
# Shows packages that need updated.
#
# Dependencies:
# - checkupdates
################################

full=""
short=""
color=""
status=0

arch=$(checkupdates | wc -l)

if [ $arch -ne 0 ]; then
	full="$arch"
	short="$arch"
fi

echo $full
echo $short
echo $color
exit $status