#!/usr/bin/env bash

################################
# Shows info about sound/volume.
# Allows simple volume controls.
#
# Dependencies:
# - pulseaudio-ctl
################################


getInfo() {
    pulseaudio-ctl full-status | cut -f $1 -d ' '
}


getVolume() {
    getInfo 1
}


isMuted() {
    muteTest=`getInfo 2`
    [[ $muteTest == 'yes' ]]
}


vol=`getVolume`

# determine icon
if [ $vol -eq 0 ]; then
    icon=
else
    if [ $vol -le 34 ]; then
        icon=
    else
        icon=
    fi
fi

echo "$icon $vol"

# determine mute status
if isMuted; then
    echo
    echo "#ff0000"
fi


case $BLOCK_BUTTON in
    # right click
    # mute/unmute
    3) pulseaudio-ctl mute ;;

    # scroll up
    # raise volume
    4) pulseaudio-ctl up ;;

    # scroll down
    # lower volume
    5) pulseaudio-ctl down ;;
esac


# Refresh the status
if [[ $BLOCK_BUTTON ]]; then
    pkill -RTMIN+10 i3blocks
fi
