#!/usr/bin/env bash

################################
# Shows current time
#
# @param {String} format: The format of the time
################################

format=${BLOCK_INSTANCE:-"%H:%M:%S"}


date +"$format"
date +"%H:%M"
