#!/usr/bin/env bash

################################
# Shows current time
#
# @param {String} format: The format of the time
# @return {Time}: Current time
################################

format=${BLOCK_INSTANCE:-"%H:%M:%S"}

date +"$format"
date +"%H:%M"
