#!/usr/bin/env bash

################################
# Shows packages that need updated.
#
# Dependencies:
# - yaourt
################################


# Refresh package lists
yaourt -Sya


arch=$(yaourt -Qu | wc -l)
aurToo=$(yaourt -Qua | wc -l)
aur=$(echo "$aurToo - $arch" | bc)


echo "ARCH: $arch, AUR: $aur"
echo "$arch/$aur"
